insert into public.districts (name, province) values
('Colombo','Western'),('Gampaha','Western'),('Kalutara','Western'),
('Kandy','Central'),('Matale','Central'),('Nuwara Eliya','Central'),
('Galle','Southern'),('Matara','Southern'),('Hambantota','Southern'),
('Jaffna','Northern'),('Kilinochchi','Northern'),('Mannar','Northern'),('Vavuniya','Northern'),('Mullaitivu','Northern'),
('Batticaloa','Eastern'),('Ampara','Eastern'),('Trincomalee','Eastern'),
('Kurunegala','North Western'),('Puttalam','North Western'),
('Anuradhapura','North Central'),('Polonnaruwa','North Central'),
('Badulla','Uva'),('Monaragala','Uva'),
('Ratnapura','Sabaragamuwa'),('Kegalle','Sabaragamuwa');

insert into public.cities (district_id, name)
select d.id, c.name from public.districts d
join (values
('Colombo','Colombo 01 - Fort'),('Colombo','Colombo 03 - Kollupitiya'),('Colombo','Colombo 04 - Bambalapitiya'),
('Colombo','Colombo 05 - Havelock Town'),('Colombo','Colombo 06 - Wellawatte'),('Colombo','Colombo 07 - Cinnamon Gardens'),
('Colombo','Dehiwala'),('Colombo','Mount Lavinia'),('Colombo','Nugegoda'),('Colombo','Maharagama'),
('Colombo','Kotte'),('Colombo','Rajagiriya'),('Colombo','Battaramulla'),('Colombo','Homagama'),
('Colombo','Piliyandala'),('Colombo','Moratuwa'),('Colombo','Kaduwela'),('Colombo','Kesbewa'),
('Gampaha','Negombo'),('Gampaha','Gampaha'),('Gampaha','Ja-Ela'),('Gampaha','Wattala'),
('Gampaha','Kelaniya'),('Gampaha','Kadawatha'),('Gampaha','Minuwangoda'),('Gampaha','Nittambuwa'),
('Gampaha','Ragama'),('Gampaha','Kiribathgoda'),('Gampaha','Veyangoda'),
('Kalutara','Kalutara'),('Kalutara','Panadura'),('Kalutara','Horana'),('Kalutara','Beruwala'),
('Kalutara','Aluthgama'),('Kalutara','Matugama'),('Kalutara','Wadduwa'),
('Kandy','Kandy'),('Kandy','Peradeniya'),('Kandy','Katugastota'),('Kandy','Gampola'),
('Kandy','Nawalapitiya'),('Kandy','Kadugannawa'),('Kandy','Digana'),('Kandy','Akurana'),('Kandy','Pilimathalawa'),
('Matale','Matale'),('Matale','Dambulla'),('Matale','Sigiriya'),('Matale','Galewela'),('Matale','Ukuwela'),('Matale','Rattota'),
('Nuwara Eliya','Nuwara Eliya'),('Nuwara Eliya','Hatton'),('Nuwara Eliya','Talawakele'),
('Nuwara Eliya','Ginigathhena'),('Nuwara Eliya','Maskeliya'),('Nuwara Eliya','Ragala'),
('Galle','Galle'),('Galle','Unawatuna'),('Galle','Hikkaduwa'),('Galle','Ambalangoda'),
('Galle','Elpitiya'),('Galle','Baddegama'),('Galle','Karapitiya'),('Galle','Bentota'),
('Matara','Matara'),('Matara','Weligama'),('Matara','Mirissa'),('Matara','Akuressa'),
('Matara','Dikwella'),('Matara','Deniyaya'),('Matara','Hakmana'),
('Hambantota','Hambantota'),('Hambantota','Tangalle'),('Hambantota','Tissamaharama'),
('Hambantota','Ambalantota'),('Hambantota','Beliatta'),('Hambantota','Weeraketiya'),
('Jaffna','Jaffna'),('Jaffna','Nallur'),('Jaffna','Chavakachcheri'),('Jaffna','Point Pedro'),
('Jaffna','Manipay'),('Jaffna','Chunnakam'),('Jaffna','Kopay'),
('Kilinochchi','Kilinochchi'),('Kilinochchi','Paranthan'),('Kilinochchi','Poonakary'),
('Mannar','Mannar'),('Mannar','Nanattan'),('Mannar','Murunkan'),
('Vavuniya','Vavuniya'),('Vavuniya','Nedunkeni'),('Vavuniya','Cheddikulam'),
('Mullaitivu','Mullaitivu'),('Mullaitivu','Oddusuddan'),('Mullaitivu','Puthukudiyiruppu'),
('Batticaloa','Batticaloa'),('Batticaloa','Kattankudy'),('Batticaloa','Eravur'),
('Batticaloa','Valaichchenai'),('Batticaloa','Kaluwanchikudy'),
('Ampara','Ampara'),('Ampara','Kalmunai'),('Ampara','Akkaraipattu'),
('Ampara','Sainthamaruthu'),('Ampara','Pottuvil'),('Ampara','Sammanthurai'),
('Trincomalee','Trincomalee'),('Trincomalee','Kinniya'),('Trincomalee','Kantale'),
('Trincomalee','Muttur'),('Trincomalee','Nilaveli'),
('Kurunegala','Kurunegala'),('Kurunegala','Kuliyapitiya'),('Kurunegala','Pannala'),
('Kurunegala','Narammala'),('Kurunegala','Wariyapola'),('Kurunegala','Melsiripura'),('Kurunegala','Polgahawela'),
('Puttalam','Puttalam'),('Puttalam','Chilaw'),('Puttalam','Wennappuwa'),
('Puttalam','Marawila'),('Puttalam','Anamaduwa'),('Puttalam','Nattandiya'),
('Anuradhapura','Anuradhapura'),('Anuradhapura','Kekirawa'),('Anuradhapura','Medawachchiya'),
('Anuradhapura','Thambuttegama'),('Anuradhapura','Eppawala'),('Anuradhapura','Mihintale'),('Anuradhapura','Galenbindunuwewa'),
('Polonnaruwa','Polonnaruwa'),('Polonnaruwa','Hingurakgoda'),('Polonnaruwa','Medirigiriya'),('Polonnaruwa','Kaduruwela'),
('Badulla','Badulla'),('Badulla','Bandarawela'),('Badulla','Ella'),('Badulla','Haputale'),
('Badulla','Welimada'),('Badulla','Mahiyanganaya'),('Badulla','Passara'),
('Monaragala','Monaragala'),('Monaragala','Wellawaya'),('Monaragala','Bibile'),
('Monaragala','Buttala'),('Monaragala','Kataragama'),
('Ratnapura','Ratnapura'),('Ratnapura','Embilipitiya'),('Ratnapura','Balangoda'),
('Ratnapura','Pelmadulla'),('Ratnapura','Eheliyagoda'),('Ratnapura','Kuruwita'),
('Kegalle','Kegalle'),('Kegalle','Mawanella'),('Kegalle','Warakapola'),
('Kegalle','Rambukkana'),('Kegalle','Dehiowita'),('Kegalle','Ruwanwella')
) as c(district, name) on c.district = d.name;

insert into public.services (slug, name, description, category, starting_price, hourly_rate, estimated_duration, display_order) values
('plumbing','Plumbing','Leak repairs, pipe replacement, bathroom and kitchen fittings, water pump and tank work handled by verified plumbers.','Plumbing',2500,1500,90,1),
('electrical','Electrical','Wiring faults, breaker and switchboard work, lighting installation and safety inspections by licensed electricians.','Electrical',3000,1800,90,2),
('masonry','Masonry','Wall repairs, tiling, plastering, concrete work and finishing carried out by experienced masons.','Masonry',4000,2000,180,3),
('ac-repair','AC Repair','Air conditioner servicing, gas refilling, deep cleaning, fault diagnosis and new unit installation.','AC Repair',3500,2200,120,4);